settings:
mode: "lp" # Есть 2 типа. Тип command использует команды для начала/конца работы. Тип lp использует плагин LuckPerms (ставьте его если у вас менеджер прав LuckPerms)
not_found_keyid: "&cНеизвестный ключ !" # Сообщение о неизвестном ключе.
not_allowed_player: "&cВас нету в списке состава !" # Сообщение о том что человека нет в списках.
reload_message: "&aПлагин перезагружен !" # Сообщение о перезагрузке.
no_work_mode: "&cВы не находитесь в режиме работы !" #Сообщение если игрок не в режиме работы
keys:
  key1: # Это нужно вводить в качестве ID для начала/конца работы.
    id: "example_id" # ID Может быть любым это просто для справки (гоавное чтобы они не повторялись).
    start_group: "modersw" # Группа из плагина LuckPerms которая будет даваться при начале работы.
    stop_group: "moder" # Группа из плагина LuckPerms которая будет даваться при конце работы.
    start_command: "/lp user {player} parent set modersw" # Команда при начале работы. {player} заменяется на ник
    stop_command: "/lp user {player} parent set moder" # Команда при конце работы. {player} заменяется на ник.
    start_message: "&aВаш аккаунт успешно идентифицирован!" # Сообщение при начале работы.
    stop_message: "&cВы вышли из режима работы!" # Сообщение при конце работы.
    start_title: "&aВаш аккаунт подтверждён!" # ТайтлБар при начале работы.
    stop_title: "&cВы вышли из режима работы!" # ТайтлБар при конце работы.
    allowed_players: # Список тех кто может ввести этот ключ.
      - "Player1"
      - "Player2"