settings:
  mode: "lp"
  only_players: "&cЭту команду может выполнять только игрок !"
  not_found_keyid: "&cНеизвестный ключ !"
  not_allowed_player: "&cВас нету в списке состава !"
  reload_message: "&aПлагин перезагружен !"
  no_work_mode: "&cВы не находитесь в режиме работы !"
  already_active: "&cВы уже находитесь в режиме работы !"
  please_specify_key: "&bУкажите ID ключа !"
keys:
  key1:
    id: "example_id"
    start_group: "modersw"
    stop_group: "moder"
    start_command: "/lp user {player} parent set modersw"
    stop_command: "/lp user {player} parent set moder"
    start_message: "&aВаш аккаунт успешно идентифицирован!"
    stop_message: "&cВы вышли из режима работы!"
    start_title: "&aВаш аккаунт подтверждён!"
    stop_title: "&cВы вышли из режима работы!"
    allowed_players:
      - "Player1"
      - "Player2"