name: SeeStaffKey
version: '1.5.0'
main: ru.gdev.seestaffkey.SeeStaffKey
api-version: '1.16'
load: STARTUP
softdepend: [LuckPerms]
authors: [GDev]
website: https://gdev.seemine.su
commands:
  ssw:
    description: Основные команды SStaffWork
    usage: /<command> [reload|help|info]
    permission: ssw.admin
  key:
    description: Управление ключами
    usage: /<command> [id|stop|help]
    permission: ssw.staff
permissions:
  ssw.admin:
    default: op
  ssw.staff:
    default: op
  seestaffkey.override:
    default: ops